language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

env:
  - PHPUNIT=7.*
  - PHPUNIT=dev-master MIN_STABILITY=dev

cache:
  directories:
    - $HOME/.composer

before_script:
  - phpenv config-rm xdebug.ini || true
  - if [[ "$MIN_STABILITY" != "" ]]; then composer config minimum-stability $MIN_STABILITY; fi
  - if [[ $(phpenv version-name) != '7.1' ]]; then composer require phpunit/phpunit:${PHPUNIT}; fi
  - if [[ $(phpenv version-name) == '7.1' ]]; then composer require phpunit/phpunit; fi

script:
  - ./vendor/bin/phpunit
